### ISSUE TITLE
memory gets full immedietly and system freezes on linux

### ISSUE THREAD

**Issue by Relected** [Michal2SAB/Bitcoin-Stealer#12]
my system freezes after running run.sh or gen.sh on void linux, i have 8 GB of ram,

 can I limit the amount of generated addresses or the allowed ram usage?

**Comment by Michal2SAB** [comment]
You can edit run.sh and decrease the sleep number from 100 to whatever lower number, so that it refreshes program faster and doesn't leak memory

**Comment by petjal** [comment]
Some dumb ideas here: https://github.com/petjal/Bitcoin-Stealer/discussions/1

**Comment by Michal2SAB** [comment]
I just looked into it again and realized something very stupid I did lol. I was reading the riches.txt file continously, every time a new wallet was generated.. I edited the code so that it reads riches.txt only once and stores all data in one variable. I haven't tested if it fixes the memory leak issue completely but I imagine it helped a bit.
