### ISSUE TITLE
does this works for mac?

### ISSUE THREAD

**Issue by ssjblue-xxx** [Michal2SAB/Bitcoin-Stealer#41]
i've got a question, is the linux thing also works for mac ?

**Comment by neverm8** [comment]
Hi Michal, thanks for your reply mate -

It’s on a standard dell 32Bit 64K processor running windows 11 -

Long story short is that a group of us got scammed quite heavily and we
have had no assistance of note from the authorities.

We’ve been looking into this for a few months now and have found a number
of my payments linked together from another one of my TXID transaction
account identifiers on the OXT.me website.

From that, I’ve traced down some large holding wallets, some of which
haven’t been touched since October last year.

Hence, I’m looking at trying to crack the vault and reclaim our losses - I
don’t look at it as stealing as the money has all been stolen from us and
other parties in the first place.

In the absence of any assistance from authorities, we’re not really left
with any other choice, so any help from you would be greatly appreciated
mate.



Cheers

**Comment by Michal2SAB** [comment]
It should work on most mac os's, but some may be too outdated and not supported though.
