### ISSUE TITLE
What if I already know the 8-9 words and their exact places in the mnemonic?

### ISSUE THREAD

**Issue by J0hannesBoe** [Michal2SAB/Bitcoin-Stealer#69]
Also, I know the address holding the funds. Any way a bot can help to crack the wallet faster?

**Comment by Michal2SAB** [comment]
If it's 12 words and you know the exact places you can just use some phrases wordlist to find the 3 other ones. But it may still take a while or forever because you'd have to get lucky with all 3 of them at once in order to detect success (generate a wallet matching the address you have). You would need to generate your address from mnemonic phrase instead of like my script does from a random hex string
